### ISSUE TITLE
64-bit Windows Issues

### ISSUE THREAD

**Issue by kognise** [mus264/264-tools#23]
I'm having some issues loading 264 Tools in 64-bit Max 8 on Windows 10. Specifically, no modules are loaded and the console displays the following error on startup:

```
Could not load package '264 Tools', 64-bit architecture unsupported.
```

I just cloned this repo directly into `~/Documents/Max 8/Packages`. Here's my Max version information:

![](https://doggo.ninja/Jvdv3p.png)

When I attempt to manually load patches like the module finder, I get errors related to `jsui: can't find file 264.helptext.js`. Happy to provide any other information required for debugging, thanks!

**Comment by delucis** [comment]
Hi @kognise!

I don’t quite remember the status of 64-bit support in Windows. I don’t have a Windows machine to test on, but it may have had something to do with Java support if I remember correctly.

Could you try changing the windows `platform` line in package-info.json to `"platform": ["ia32", "x64"]` and seeing if it will load correctly when you reopen Max? Here’s the current configuration:

https://github.com/mus264/264-tools/blob/dd26680d18929b06a734f1436ef23a17b3dda4eb/package-info.json#L18-L20

I think that line is telling Max 64-bit isn’t supported, so changing it may allow Max to load the package, but I don’t know if it will then actually run as expected.

If the problem is Java support, it would be nice to remove use of Java completely (it’s only used for some filesystem management) and use Node.js instead which should work perfectly across Max 8.

**Comment by kognise** [comment]
Thanks! I changed that line, looks like everything is loading fine now - the examples I've tested so far seem to be working. Is there anything specifically I should try to see if something breaks?

**Comment by delucis** [comment]
Nice! If it was a Java issue, try opening the help file for one of the sound file modules (`264.sfplay~` for example). That should run the file system code. You could also play around with `264.grains~`, `264.loop~` and `264.pitchtrack~`, which use externals, to double check they work in 64-bit.
